// This file is automatically generated by qtc from "error_page.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line ../views/error_page.qtpl:1
package views

//line ../views/error_page.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

// Error page template. Implements BasePage methods.
//

//line ../views/error_page.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line ../views/error_page.qtpl:4
type ErrorPage struct {
	// inherit from base page, so its' title is used in error page.
	BasePage

	// error path
	Path []byte
	Msg  []byte
}

//line ../views/error_page.qtpl:15
func (p *ErrorPage) StreamBody(qw422016 *qt422016.Writer) {
	//line ../views/error_page.qtpl:15
	qw422016.N().S(`
	<h1>Error page</h1>
	</div>
		<p>`)
	//line ../views/error_page.qtpl:18
	qw422016.E().Z(p.Msg)
	//line ../views/error_page.qtpl:18
	qw422016.N().S(`</p>.
	</div>
	Base page body: `)
	//line ../views/error_page.qtpl:20
	p.BasePage.StreamBody(qw422016)
	//line ../views/error_page.qtpl:20
	qw422016.N().S(`
`)
//line ../views/error_page.qtpl:21
}

//line ../views/error_page.qtpl:21
func (p *ErrorPage) WriteBody(qq422016 qtio422016.Writer) {
	//line ../views/error_page.qtpl:21
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line ../views/error_page.qtpl:21
	p.StreamBody(qw422016)
	//line ../views/error_page.qtpl:21
	qt422016.ReleaseWriter(qw422016)
//line ../views/error_page.qtpl:21
}

//line ../views/error_page.qtpl:21
func (p *ErrorPage) Body() string {
	//line ../views/error_page.qtpl:21
	qb422016 := qt422016.AcquireByteBuffer()
	//line ../views/error_page.qtpl:21
	p.WriteBody(qb422016)
	//line ../views/error_page.qtpl:21
	qs422016 := string(qb422016.B)
	//line ../views/error_page.qtpl:21
	qt422016.ReleaseByteBuffer(qb422016)
	//line ../views/error_page.qtpl:21
	return qs422016
//line ../views/error_page.qtpl:21
}
